controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # List your controllers here
    camera_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

camera_controller:
  ros__parameters:
    joints:
      - camera_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

mecanum_drive_controller:
  ros__parameters:
    use_sim_time: true
    
    # Joint Names
    front_left_wheel_command_joint_name: "Revolute_2"
    front_right_wheel_command_joint_name: "Revolute_1"
    rear_left_wheel_command_joint_name: "Revolute_3"
    rear_right_wheel_command_joint_name: "Revolute_4"

    # NEW NESTED KINEMATICS BLOCK
    kinematics:
      wheels_radius: 0.0638
      sum_of_robot_center_projection_on_X_Y_axis: 0.4488 # (wheelbase + separation) / 2

    # Odometry and TF
    odom_frame_id: odom
    base_frame_id: base_footprint
    publish_rate: 50.0
    open_loop: false
    enable_odom_tf: true

    # Interface handling
    use_stamped_vel: false